# Generated by Django 4.2 on 2023-07-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_good_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='good',
            name='article',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cat1',
            field=models.BigIntegerField(default=0, verbose_name='id раздела 1-ого уровня'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cat2',
            field=models.BigIntegerField(default=0, verbose_name='id раздела 2-ого уровня'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cat3',
            field=models.BigIntegerField(default=0, verbose_name='id раздела 3-ого уровня'),
        ),
        migrations.AlterField(
            model_name='good',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Каталожный номер'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='good',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='good',
            name='in_stock',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6, verbose_name='Кол-во на складе'),
        ),
        migrations.AlterField(
            model_name='good',
            name='is_good',
            field=models.BooleanField(default=True, verbose_name='Товар/ раздел'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='good',
            name='supplier',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Поставшик'),
        ),
    ]
